<a href="https://colab.research.google.com/github/gplinkage/Core-Python/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [5]:
array = np.array([1, 2, 3, 4, 5 ,6])
print(array)

[1 2 3 4 5 6]


In [6]:
print (np.__version__)

1.26.4


In [7]:
import pandas as pd


In [8]:
print(pd.__version__)

2.2.2


In [9]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
print ('%d bytes'%(v.size * v.itemsize))

80 bytes


In [15]:
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [16]:
 v= np.zeros(10)
 print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
v[5]=1
print(v)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [22]:
v = np.arange(10, 30, 2)
print(v)

[10 12 14 16 18 20 22 24 26 28]


In [25]:
v= v[::-1]
print(v)

[28 26 24 22 20 18 16 14 12 10]


In [27]:
v = np.arange(9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
nz= np.nonzero([1, 2, 4, 5, 0, 2, 0, 43, 56, 100])
print(nz)

(array([0, 1, 2, 3, 5, 7, 8, 9]),)


In [30]:
v = np.eye(5)
print (v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [36]:
v = np.random.random(10)
v

array([0.42517974, 0.64579602, 0.2618613 , 0.93442287, 0.10447883,
       0.45857167, 0.18319023, 0.02267018, 0.23127947, 0.66108487])

In [37]:
v = np.random.random((10,10))
print(v)

[[0.28077517 0.31964019 0.62489741 0.10527323 0.40368118 0.42376672
  0.22058538 0.4694834  0.49323069 0.89000861]
 [0.77606552 0.88578228 0.60548509 0.290882   0.43572033 0.41814839
  0.45285999 0.34584885 0.77101805 0.4965358 ]
 [0.91974457 0.56301812 0.53038489 0.18964354 0.53868523 0.79249134
  0.29903861 0.38069715 0.23441545 0.19582771]
 [0.81884278 0.00119187 0.79317966 0.68703584 0.04631473 0.91002078
  0.44799455 0.43352481 0.79859193 0.51354341]
 [0.16179677 0.82709451 0.90138964 0.9586253  0.99582939 0.53890633
  0.28214918 0.85064307 0.85066358 0.66653414]
 [0.79268639 0.23674377 0.17403487 0.39030161 0.36694926 0.88433831
  0.12630262 0.05648347 0.66633683 0.2936839 ]
 [0.04463119 0.29423912 0.11813079 0.24215626 0.7702251  0.08513214
  0.11423039 0.34005032 0.21954997 0.95576956]
 [0.71630547 0.78753654 0.00111025 0.99849281 0.6862545  0.58529433
  0.08988021 0.34770084 0.34939353 0.24878915]
 [0.57963534 0.34539848 0.44453844 0.50146256 0.25795498 0.26969028
  0.83159094

In [44]:
v = np.random.random((10,10,3))
print(v)

[[[0.9955989  0.49452939 0.65897213]
  [0.00462797 0.36657953 0.89532328]
  [0.67066913 0.72445124 0.81360756]
  [0.1051139  0.31861246 0.97329543]
  [0.66892595 0.08388148 0.260695  ]
  [0.88571536 0.71208736 0.55175399]
  [0.50077523 0.70304636 0.88822255]
  [0.5484004  0.33604581 0.35420145]
  [0.68842456 0.69211142 0.65376469]
  [0.74352145 0.39548759 0.10913827]]

 [[0.65527347 0.32711815 0.58403097]
  [0.67537961 0.6540518  0.21831121]
  [0.99292436 0.86900117 0.742484  ]
  [0.76178326 0.31205716 0.20418784]
  [0.83092779 0.18688079 0.37230109]
  [0.73216013 0.18985544 0.64680142]
  [0.42732428 0.76050324 0.9474642 ]
  [0.96881833 0.20773541 0.53643312]
  [0.65507571 0.21282437 0.40623051]
  [0.12446372 0.32592154 0.04984413]]

 [[0.28142923 0.4930334  0.92656903]
  [0.36460389 0.1881962  0.71421664]
  [0.72545564 0.57575795 0.81143031]
  [0.76730948 0.33301124 0.08669778]
  [0.75413275 0.14382653 0.86100046]
  [0.19668751 0.0608126  0.09242206]
  [0.94718799 0.98939117 0.4326863

In [45]:
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9991153964383259 0.003141325125183392


In [48]:
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)

0.3861279036514928


In [49]:
 v = np.ones((10, 10))
 print(v)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [50]:
3 * 0.1

0.30000000000000004

In [52]:
np.sqrt(144)

12.0

In [58]:
z = np.diag(1+np.arange(5), k=0)
print(z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [59]:
# Create a 5x5 matrix with zeros

z = np.zeros((5,5))
# set values at the diagonal
values = [1, 2, 3, 4, 5]
np.fill_diagonal(z, values)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [2]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [6]:
z = np.zeros((3,7,8))
print(z)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [7]:
# Normalize a 5x5 random matrix

z= np.random.random((5,5))
zmax, zmin= z.max(), z.min()
z= (z-zmin)/(zmax-zmin)
print(z)

[[0.27828916 0.90273428 0.56057572 0.14127888 0.00452794]
 [0.53249965 0.18686377 0.27919889 0.72687817 0.89359691]
 [0.54060604 0.6165883  0.1533044  0.80289133 0.        ]
 [0.03335232 0.51634407 0.04425914 0.16758825 0.35583913]
 [0.57264612 0.97159797 0.0248156  1.         0.10203253]]


In [8]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte,1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-8-09c9ead1d7a9>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte,1),


In [9]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [10]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [12]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
z= np.arange(11)
z[(3<z)&(z<=8)] *=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [24]:
# What is the output of the following script?
print(sum(range(2),-1))
from numpy import *
print(np.sum(range(5),-1))


1
10


In [22]:
print(range(2),-1)

range(0, 2) -1


In [25]:
# How to find common values between two arrays?

z1= np.random.randint(0, 10, 10)
z2= np.random.randint(0, 10, 10)
print(np.intersect1d(z1, z2))

[1 4 5 6 9]


In [30]:
# How to get the dates of yesterday, today and tomorrow?
today = np.datetime64("today", "D")
print(today)
yesterday = np.datetime64("today", "D") - np.timedelta64(1,'D')
print(yesterday)
tomorrow = np.datetime64("today", "D")+np.timedelta64(1, "D")
print(tomorrow)

2024-12-21
2024-12-20
2024-12-22


In [32]:
# How to get all the dates corresponding to the month of July 2023?

Z = np.arange('2023-07', '2023-08', dtype= 'datetime64[D]')
print(Z)

['2023-07-01' '2023-07-02' '2023-07-03' '2023-07-04' '2023-07-05'
 '2023-07-06' '2023-07-07' '2023-07-08' '2023-07-09' '2023-07-10'
 '2023-07-11' '2023-07-12' '2023-07-13' '2023-07-14' '2023-07-15'
 '2023-07-16' '2023-07-17' '2023-07-18' '2023-07-19' '2023-07-20'
 '2023-07-21' '2023-07-22' '2023-07-23' '2023-07-24' '2023-07-25'
 '2023-07-26' '2023-07-27' '2023-07-28' '2023-07-29' '2023-07-30'
 '2023-07-31']


In [35]:
Z = np.random.uniform(0,10,10)
print(Z.astype(int))

[1 9 5 0 9 7 4 5 9 8]


In [36]:
# Create a 5x5 matrix with row values ranging from 0 to 4
z= np.zeros((5,5))
z+= np.arange(5)
prin

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [38]:
from types import GeneratorType
# Consider a generator function that generates 10 integers and use it to build an array

def generator():
  for i in range(10):
    yield iz = np.fromiter(generator(), dtype= float, count = 1)


In [39]:
from types import GeneratorType
# Consider a generator function that generates 10 integers and use it to build an array

def generator():
  for i in range(10):
    yield i

In [41]:
z = np.fromiter(generator(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [42]:
# Create a random vector of size 10 and sort it

z= np.random.random(10)
z.sort()
print(z)


[0.1861398  0.27686572 0.30808997 0.30829786 0.4256598  0.46436422
 0.54444085 0.78260486 0.80794054 0.97932195]
